file_format: "1"
id: idiot12_wireless
name: Idiot12 Wireless
type: shield
url: https://github.com/wenbang24/idiot12_wireless
requires: [nrf52840]
features:
    - keys
siblings:
    - idiot12_wireless_left
    - idiot12_wireless_right
